E-Tombola/Areas/Admin/Controllers/TombolyController.cs
using E_Tombola.Models.Core;
using E_Tombola.Models.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Tombola.Areas.Admin.Controllers
{
    [Authorize(Roles="Administrator")]
    public class TombolyController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Admin/Tomboly/
        public ActionResult Index()
        {
            IList<Raffle> raffles = unitOfWork.RaffleRepository.Get().ToList();
            return View(raffles);
        }

        //
        // GET: /Admin/Tomboly/Nova
        public ActionResult Nova()
        {
            Raffle newRaffle = new Raffle();
            newRaffle.StartOfTicketSale = DateTime.Now;
            newRaffle.EndOfTicketSale = DateTime.Now.AddDays(6);
            newRaffle.DateOfDrawing = DateTime.Now.AddDays(7);
            return View(newRaffle);
        }

        //
        // POST :/Admin/Tomboly/Nova
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nova(Raffle newRaffle, HttpPostedFileBase file)
        {
            newRaffle.DateOfCreation = DateTime.Now;
            if(newRaffle.StartOfTicketSale>newRaffle.EndOfTicketSale || newRaffle.EndOfTicketSale>newRaffle.DateOfDrawing)
            {
                ModelState.AddModelError("", "Skontrolujte dátumy");
            }

            if (ModelState.IsValid)
                {
                if(file!=null && file.ContentLength>0)
                {
                    string url = "~/Uploads/" + newRaffle.Title + "-" + DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(file.FileName);
                    string filePath = Server.MapPath(url);
                    file.SaveAs(filePath);
                    newRaffle.ImageURL = url;
                }
                else
                {
                    newRaffle.ImageURL = "~/Uploads/Default-raffle.jpg";
                }
                    unitOfWork.RaffleRepository.Insert(newRaffle);
                    unitOfWork.Save();
                    TempData["msg"] = "Tombola bola pridaná";
                    return RedirectToAction("Index");
                }
            else
            {
                ModelState.AddModelError("", "Nepodarilo sa uložiť záznam. Skontrolujte správnosť údajov.");
                return View(newRaffle);
            }


        }

        //
        // GET /Admin/Tomboly/Detail/1
        public ActionResult Detail(int Id)
        {
            Raffle raffleToView = unitOfWork.RaffleRepository.GetByID(Id);
            if (raffleToView==null)
            {
                return View("Error");
            }
            else
            {
                return View(raffleToView);
            }
        }

        //
        // GET /Admin/Tomboly/Edituj/1
        public ActionResult Edituj(int Id)
        {
            Raffle raffleToEdit = unitOfWork.RaffleRepository.GetByID(Id);
            if(raffleToEdit==null)
            {
                return View("Error");
            }
            else
            {
                return View(raffleToEdit);
            }
        }

        //
        // POST /Admin/Tomboly/Edituj/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edituj(Raffle RaffleToEdit, HttpPostedFileBase file)
        {
            TryUpdateModel(RaffleToEdit);
            if(ModelState.IsValid)
            {
                if(file!=null && file.ContentLength>0)
                {
                    if (!RaffleToEdit.ImageURL.Equals("~/Uploads/Default-raffle.jpg"))
                    {
                        System.IO.File.Delete(Server.MapPath(RaffleToEdit.ImageURL));
                    }
                    string url = "~/Uploads/" + RaffleToEdit.Title + "-" + DateTime.Now.ToString("yyyyMMddHHmmssfff") + Path.GetExtension(file.FileName);
                    string path = Server.MapPath(url);
                    file.SaveAs(path);
                    RaffleToEdit.ImageURL = url;
                    

                }
                unitOfWork.RaffleRepository.Update(RaffleToEdit);
                unitOfWork.Save();
                TempData["msg"] = "Tombola bola upravená";
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Skontrolujte správanosť zadaných údajov");
                return View(RaffleToEdit);
            }
        }

        //
        // GET /Admin/Tomboly/Vymaz/1
        [HttpGet]
        public ActionResult Vymaz(string submitButton, int Id)
        {
            Raffle raffleToDelete = unitOfWork.RaffleRepository.GetByID(Id);
            if(raffleToDelete==null)
            {
                return RedirectToAction("Error");
            }
            else
            {
                if(raffleToDelete.Tickets.Count>0)
                {
                    ModelState.AddModelError("", "Tombola sa nedá vymazať. Sú už predané lístky.");
                }
                return View(raffleToDelete);
            }
        }

        //
        // POST /Admin/Tomboly/Vymaz/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Vymaz(int Id)
        {
            string imgUrl = unitOfWork.RaffleRepository.GetByID(Id).ImageURL;
            if(!imgUrl.Equals("~/Uploads/Default-raffle.jpg"))
            {
                System.IO.File.Delete(Server.MapPath(imgUrl));
            }
            unitOfWork.RaffleRepository.Delete(Id);
            unitOfWork.Save();
            TempData["msg"] = "Tombola bola vymazaná";
            return RedirectToAction("Index");
        }

        public ActionResult Zrebovanie(int? id)
        {
            if((bool)HttpContext.Application["Zrebovanie"])
            {
                id = (int)HttpContext.Application["ZrebovanieId"];
            }
            Raffle raffle = unitOfWork.RaffleRepository.GetByID(id);
            if(raffle==null)
            {
                return View("Error");
            }
            return View(raffle);
        }

        [HttpPost]
        public ActionResult Zrebovanie(Raffle model, string Command)
        {
            Raffle raffle = unitOfWork.RaffleRepository.GetByID(model.Id);
            switch (Command)
            {
                case "Start Stream":
                    HttpContext.Application["Zrebovanie"] = true;
                    HttpContext.Application["ZrebovanieId"] = model.Id;
                    break;
                case "Stop Stream":
                    HttpContext.Application["Zrebovanie"] = false;
                    HttpContext.Application["ZrebovanieId"] = null;
                    break;
                default:
                    break;
            }
            
            return View(raffle);
        }

        public ActionResult ELos(int id)
        {
            List<int> model = unitOfWork.TicketRepository.Get().Where(m => m.RaffleId==id).Select(m => m.Id).ToList();
            ViewBag.RaffleId = id;
            return View(model);
        }

        public ActionResult Vysledok(int raffleId, int winnerTicketId)
        {
            Raffle raf = unitOfWork.RaffleRepository.GetByID(raffleId);
            if (raf != null)
            {
                raf.WinnerTicketId = winnerTicketId;
                unitOfWork.RaffleRepository.Update(raf);
                unitOfWork.Save();
                TempData["msg"] = "Víťaz tomboly bol úspešne vylosovaný a zapísaný";
                // email
                return RedirectToAction("Zrebovanie");
            }
            return View("Error");
        }
	}
}

E-Tombola/Areas/Admin/Views/Tomboly/Detail.cshtml
@model E_Tombola.Models.Core.Raffle

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>@Html.DisplayFor(model => model.Title)</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImageURL)" alt="Tombola" width="200" height="200"/>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price) 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price) &euro;
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceOfTicket)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceOfTicket) Kreditov
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfCreation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDrawing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDrawing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartOfTicketSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartOfTicketSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndOfTicketSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndOfTicketSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WinnerTicketId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WinnerTicketId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfTickets)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Upraviť", "Edituj", new { id = Model.Id }, new { @class = "btn btn-default" })
    <a class="btn btn-danger " aria-label="Right Align" href=@Url.Action("Zrebovanie", "Tomboly", new { id = Model.Id })>
        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
        Žrebuj

    </a>
</p>
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

E-Tombola/Areas/Admin/Views/Tomboly/ELos.cshtml
@model IEnumerable<int>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
    <title>ELos</title>
</head>
<body>
    <div><p>Žrebovie zastavíte stlačením ľub. klávesy</p></div>
    <div id="change" style="font-size:30em"> 
        @Html.Hidden("winner")
    </div>

    <div id="result"></div>
    
    <script>
        var array = @Html.Raw(Json.Encode(Model));
        
        var inter = setInterval(update, 75);

        i=0;
        function update() {
            $("#change").html(array[i]);
            i++;
            if(i>array.length) i=0;           
        }
        $( "*" ).keypress(function() {
            clearInterval(inter);
            w = $("#change").html();
            $("#result").html("<a href='/Admin/Tomboly/Vysledok?raffleId="+@ViewBag.RaffleId+"&winnerTicketId="+w+"' >Zapisat</a>")
        });
    </script>
</body>
</html>

E-Tombola/Areas/Admin/Views/Tomboly/Edituj.cshtml
@model E_Tombola.Models.Core.Raffle

@{
    ViewBag.Title = "Edituj";
}

<h2>Edituj</h2>


@using (Html.BeginForm("Edituj", "Tomboly",
                    FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.DateOfCreation)
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.Title)</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ImageURL)
                <img src="@Url.Content(Model.ImageURL)" width="200" height="200" />
                <input type="file" id="file" name="file" />
                @Html.ValidationMessageFor(model => model.ImageURL)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price)
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceOfTicket, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceOfTicket)
                @Html.ValidationMessageFor(model => model.PriceOfTicket)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.StartOfTicketSale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartOfTicketSale)
                @Html.ValidationMessageFor(model => model.StartOfTicketSale)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndOfTicketSale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndOfTicketSale)
                @Html.ValidationMessageFor(model => model.EndOfTicketSale)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfDrawing, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfDrawing)
                @Html.ValidationMessageFor(model => model.DateOfDrawing)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Uložiť" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-danger" aria-label="Left Align" href="@Url.Action("Zrebovanie", new { id = Model.Id })">
        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
        Žrebovať
    </a>
</div>
<hr />
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    // will trigger when the document is ready
    $('#StartOfTicketSale').datetimepicker({
        format: 'd. F. Y  H:i',
        lang: "sk"
    }); //Initialise any date pickers
    $('#EndOfTicketSale').datetimepicker({
        format: 'd. F. Y H:i',
        lang: "sk",
        DefaultDate: "@{ Model.EndOfTicketSale.ToShortDateString();}"

    });
    $('#DateOfDrawing').datetimepicker({
        format: 'd. F. Y H:i',
        lang: "sk"
    });
</script>

E-Tombola/Areas/Admin/Views/Tomboly/Index.cshtml
@model IEnumerable<E_Tombola.Models.Core.Raffle>

@{
    ViewBag.Title = "Tomboly";
}
    <h2>Tomboly</h2>

    <p>
        <a class="btn btn-default pull-right" aria-label="Right Align" href=@Url.Action("Nova", "Tomboly")>
         Pridať tombolu
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </a>      
    </p>

    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PriceOfTicket)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.DateOfDrawing)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.StartOfTicketSale)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.EndOfTicketSale)
                    </th>
                    <th>
                        Počet lístkov
                    </th>
                    <th>Akcie</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PriceOfTicket)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateOfDrawing)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartOfTicketSale)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndOfTicketSale)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NumberOfTickets)
                        </td>
                        <td>
                            @Html.ActionLink(" ", "Detail", new { id = item.Id }, new { @class = "btn btn-default glyphicon glyphicon-zoom-in", @title = "Detail" })
                      
                            @Html.ActionLink(" ", "Edituj", new { id = item.Id }, new { @class = "btn btn-default glyphicon glyphicon-pencil", @title = "Edituj" })
                            
                            @Html.ActionLink(" ", "Vymaz", new { id = item.Id }, new { @class = "btn btn-default glyphicon glyphicon-trash", @title = "Vymaž" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        
</div>

E-Tombola/Areas/Admin/Views/Tomboly/Nova.cshtml
@model E_Tombola.Models.Core.Raffle

@{
    ViewBag.Title = "Nova";
}

<h2>Nová tombola</h2>


@using (Html.BeginForm("Nova", "Tomboly",
                    FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tombola</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.ImageURL)
                <input type="file" id="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price) Eur
                @Html.ValidationMessageFor(model => model.Price)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceOfTicket, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceOfTicket)
                @Html.ValidationMessageFor(model => model.PriceOfTicket)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartOfTicketSale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartOfTicketSale, new { @class = "datetimepicker" })
                @Html.ValidationMessageFor(model => model.StartOfTicketSale)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndOfTicketSale, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndOfTicketSale, new { @class = "datetimepicker" })
                @Html.ValidationMessageFor(model => model.EndOfTicketSale)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfDrawing, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfDrawing, new { @class = " datetimepicker" })
                @Html.ValidationMessageFor(model => model.DateOfDrawing)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Uložiť" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">      
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    // will trigger when the document is ready
    $('#StartOfTicketSale').datetimepicker({
        format: 'd. F. Y  H:i',
        lang: "sk",
        
    }); //Initialise any date pickers
    $('#EndOfTicketSale').datetimepicker({
        format: 'd. F. Y H:i',
        lang: "sk",
    });
    $('#DateOfDrawing').datetimepicker({
        format: 'd. F. Y H:i',
        lang: "sk"
    });
</script>

E-Tombola/Areas/Admin/Views/Tomboly/Vymaz.cshtml
@model E_Tombola.Models.Core.Raffle

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Title);
}


<h3>Naozaj chcete odstrániť túto tombolu?</h3>
<div>
    <h4>Vymazať</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImageURL)" width="200" height="200" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceOfTicket)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceOfTicket)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfCreation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDrawing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfDrawing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartOfTicketSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartOfTicketSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndOfTicketSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndOfTicketSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WinnerTicketId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WinnerTicketId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfTickets)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @Html.HiddenFor(model => model.Id)
            <button type="submit" class="btn btn-default ">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Vymazať
            </button> |
            <a class="btn btn-default" aria-label="Left Align" href="../Index">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                Späť
            </a>
        </div>
    }
</div>

E-Tombola/Areas/Admin/Views/Tomboly/Zrebovanie.cshtml
@model E_Tombola.Models.Core.Raffle

@{
    ViewBag.Title = "Zrebovanie";
}

<h1>Žrebovanie <small>@Model.Title</small></h1>

<div>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            <img src="@Url.Content(Model.ImageURL)" width="150" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceOfTicket)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceOfTicket)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfCreation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfCreation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfDrawing)
        </dt>

        <dd>
            <strong>@Html.DisplayFor(model => model.DateOfDrawing)</strong>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartOfTicketSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartOfTicketSale)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndOfTicketSale)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndOfTicketSale)
        </dd>



        

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfTickets)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfTickets)
        </dd>

        
        <dt>
            @Html.DisplayNameFor(model => model.WinnerTicketId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WinnerTicketId)
        </dd>

    </dl>
</div>
<hr />
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            @if(!(bool)Context.Application["Zrebovanie"])
            { 
                <input type="submit" name="Command" value="Start Stream" class="btn btn-success" />
            }
            else 
            {
             <input type="submit" name="Command" value="Stop Stream" class="btn btn-danger" /> @:| @Html.ActionLink("E-Losovanie", "ELos", new { id = Model.Id }, new { target="_blank", @class = "btn btn-success" }) | @Html.ActionLink("Ručné losovanie", "ALos", new { id = Model.Id }, new { target="_blank", @class = "btn btn-success" })
            }
            <div>
                <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
                    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                    Späť
                </a>
            </div>
        </div>
    }
</div>