E-Tombola/Areas/Admin/Controllers/SpravyController.cs
using E_Tombola.Areas.Admin.Models;
using E_Tombola.Areas.Admin.Models.MailService;
using E_Tombola.Models.Core;
using E_Tombola.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace E_Tombola.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class SpravyController : Controller
    {

        private Mailer mailService = new Mailer();
        private UnitOfWork unitOfWork = new UnitOfWork();

        //
        // GET: /Admin/Spravy/
        public ActionResult Index()
        {
            ViewBag.NewCount = unitOfWork.MessageRepository.Get().Where(m => m.Type == "new").Count();
            return View();
        }

        //
        // GET: /Admin/Spravy/Nova/adress
        public ActionResult Nova(string address)
        {
            SingleMailViewModel model = new SingleMailViewModel();
            if (address != null)
            {
                model.To = address;
            }
            model.From = "info@e-tombola.sk";
            List<string> adresses = unitOfWork.ProfileRepository.Get().Select(s => s.UserName).ToList();
            ViewBag.Adresses = adresses;
            return View(model);
        }

        //
        // POST: /Admin/Spravy/Nova/address
        [HttpPost]
        public ActionResult Nova(string address, SingleMailViewModel model)
        {
            if(ModelState.IsValid)
            {
                MailMessage msg = new MailMessage();
                msg.From = new MailAddress(model.From);
                msg.To.Add(model.To);
                msg.Subject = model.Subject;
                msg.Body = model.Body;
                msg.IsBodyHtml = true;
                mailService.Send(msg);
                Message message = new Message();
                message.From = model.From;
                message.To = model.To;
                message.Subject = model.Subject;
                message.Body = model.Body;
                message.Type = "sent";
                message.Time = DateTime.Now;
                unitOfWork.MessageRepository.Insert(message);
                unitOfWork.Save();
                TempData["msg"] = "Správa bola úspešne odoslaná a uložená";
                return RedirectToAction("Index");
            }
            else
            {
                List<string> adresses = unitOfWork.ProfileRepository.Get().Select(s => s.UserName).ToList();
                ViewBag.Adresses = adresses;
                return View(model);
            }
        }

        //
        // GET /Admin/Spravy/Hromadna

        public ActionResult Hromadna()
        {
            SingleMailViewModel model = new SingleMailViewModel();
            model.From = "info@e-tombola.sk";
            int adresses = unitOfWork.ProfileRepository.Get().Select(s => s.UserName).Count();
            ViewBag.Receivers =  adresses;
            return View(model);
        }

        //
        // POST: /Admin/Spravy/Hromadna

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Hromadna(SingleMailViewModel model)
        {
            List<string> adresses = unitOfWork.ProfileRepository.Get().Select(s => s.UserName).ToList();
            if (ModelState.IsValid)
            {                
                MailMessage msg = new MailMessage();
                msg.From = new MailAddress(model.From);
                foreach (var a in adresses)
                {
                    msg.To.Add(a);
                }
                msg.Subject = model.Subject;
                msg.Body = model.Body;
                msg.IsBodyHtml = true;
                mailService.Send(msg);
                Message message = new Message();
                message.From = model.From;
                message.To = "All";
                message.Subject = model.Subject;
                message.Body = model.Body;
                message.Type = "sent";
                message.Time = DateTime.Now;
                unitOfWork.MessageRepository.Insert(message);
                unitOfWork.Save();
                TempData["msg"] = "Hromadná správa bola úspešne odoslaná a uložená";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Adresses = adresses;
                return View(model);
            }
        }

        //
        // GET /Admin/Spravy/Odoslane
        public ActionResult Odoslane()
        {
            IList<Message> messages = unitOfWork.MessageRepository.Get().Where(m => m.Type == "sent").ToList();
            return View(messages);
        }


        public ActionResult Prijate()
        {
            ReceivedMessagesViewModel model = new ReceivedMessagesViewModel();
            model.newMessages = unitOfWork.MessageRepository.Get().Where(m => m.Type == "new").ToList();
            model.receivedMessages = unitOfWork.MessageRepository.Get().Where(m => m.Type == "viewed").ToList();
            return View(model);
        }

        //
        // GET /Admin/Spravy/Detail/5

        public ActionResult Detail(int id)
        {
            Message msg = unitOfWork.MessageRepository.GetByID(id);
            if (msg != null)
            {
                if (msg.Type == "new")
                {
                    msg.Type = "viewed";
                    unitOfWork.MessageRepository.Update(msg);
                    unitOfWork.Save();
                    TempData["msg"] = "Správa prečítaná";
                }
                return View(msg);
            }
            else return RedirectToAction("Error");
        }
	}
}

E-Tombola/Areas/Admin/Views/Spravy/Detail.cshtml
@model E_Tombola.Models.Core.Message

@{
    ViewBag.Title = "Detail";
}

<h2>Detail <small>správy</small></h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.From)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.From)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.To)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.To)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>




    </dl>
</div>
@if (Model.Type != "sent")
{
    <div>
        <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Nova", new { address = Model.From })">
            <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
            Odpovedať
        </a>
    </div>
}
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

E-Tombola/Areas/Admin/Views/Spravy/Hromadna.cshtml
@model E_Tombola.Areas.Admin.Models.SingleMailViewModel

@{
    ViewBag.Title = "Hromadná správa";
}

<h2>Hromadná správa</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Počet príjemcov <span class="badge">@ViewBag.Receivers</span></h4>
        <hr />
        <p>Odošle správu všetkým (@ViewBag.Receivers) zákazníkom</p>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.From, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.From, new { @class = "full-width" })
                @Html.ValidationMessageFor(model => model.From)
            </div>
        </div>

        @Html.Hidden("To","-")

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Subject, new { @class = "full-width" })
                @Html.ValidationMessageFor(model => model.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "full-width", @rows = "10" })
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Odoslať" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

E-Tombola/Areas/Admin/Views/Spravy/Index.cshtml
@{
    ViewBag.Title = "Správy";
}

<h2><span class="glyphicon glyphicon-envelope "></span> Centrum správ</h2>



<div class="row">
    <div class="col-sm-7 col-md-6">
        <div class="thumbnail">
            <img data-src="holder.js/300x300" alt="...">
            <div class="caption">
                <h3>Jednoduchá správa</h3>
                <p>Správa pre jedného príjemcu</p>
                <p><a href="@Url.Action("Nova")" class="btn btn-primary" role="button">Napísať</a></p>
            </div>
        </div>
    </div>

    <div class="col-sm-7 col-md-6">
        <div class="thumbnail">
            <img data-src="holder.js/300x300" alt="...">
            <div class="caption">
                <h3>Hromadná správa</h3>
                <p>Správa pre viacerých príjemcov</p>
                <p><a href="@Url.Action("Hromadna")" class="btn btn-primary" role="button">Napísať</a></p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-7 col-md-6" >
        <div class="thumbnail">
            <img data-src="holder.js/300x300" alt="...">
            <div class="caption">
                <h3>Prijaté správy</h3>
                <p>Správy prijaté od zákazníkov</p>
                <p><a href="@Url.Action("Prijate")" class="btn btn-primary" role="button"><span class="badge">@ViewBag.NewCount</span> Zobraziť</a></p>
            </div>
        </div>
    </div>

    <div class="col-sm-7 col-md-6">
        <div class="thumbnail">
            <img data-src="holder.js/300x300" alt="...">
            <div class="caption">
                <h3>Odoslané správy</h3>
                <p>Všetky odoslané správy</p>
                <p><a href="@Url.Action("Odoslane")" class="btn btn-primary" role="button"> Zobraziť</a></p>
            </div>
        </div>
    </div>
</div>

E-Tombola/Areas/Admin/Views/Spravy/Nova.cshtml
@model E_Tombola.Areas.Admin.Models.SingleMailViewModel

@{
    ViewBag.Title = "Nova";
}

<h2>Nová <small>Správa</small></h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Html.DisplayFor(model => model.To)</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.From, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.From, new { @class = "full-width disabled" })
                @Html.ValidationMessageFor(model => model.From)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.To, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.To, new { @class = "full-width" })
                @Html.ValidationMessageFor(model => model.To)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Subject, new { @class = "full-width" })
                @Html.ValidationMessageFor(model => model.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Body, new { @class = "full-width", @rows = "10" } )
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Odoslať" class="btn btn-success " />
            </div>
        </div>
    </div>
}
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

@section Scripts{
    @{ 
    <script type="text/javascript">
        adr = @Html.Raw(Json.Encode(ViewBag.Adresses))
        $("#To").autocomplete(
            {
                source: [adr]
            })
    </script>
          }}

E-Tombola/Areas/Admin/Views/Spravy/Odoslane.cshtml
@model IEnumerable<E_Tombola.Models.Core.Message>

@{
    ViewBag.Title = "Odoslané správy";
}

<h2>Odoslané <small>správy</small></h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.To)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.To)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>

            <td>
                @Html.ActionLink(" ", "Detail", new { id = item.MessageId }, new { @class = "btn btn-default glyphicon glyphicon-zoom-in", @title = "Detail" })
            </td>
        </tr>
    }

</table>
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

E-Tombola/Areas/Admin/Views/Spravy/Prijate.cshtml
@model E_Tombola.Areas.Admin.Models.ReceivedMessagesViewModel

@{
    ViewBag.Title = "Prijate";
}

<h2>Prijaté správy <small><span class="badge">@Model.newMessages.Count</span></small></h2>

<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">Neprečítané správy</h3>
    </div>
    <div class="panel-body">

    </div>
    <table class="table">
        <tr>
            <th>
                Od
            </th>
            <th>
                Predmet
            </th>
            <th>
                Čas
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.newMessages)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.From)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>

                <td>
                    <a class="btn btn-default " aria-label="Right Align" href=@Url.Action("Detail", "Spravy")>
                        <span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>
                        Prečítať
                  
                    </a> 
                </td>
            </tr>
        }

    </table>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Prečítané správy</h3>
    </div>
    <div class="panel-body">

    </div>
    <table class="table">
        <tr>
            <th>
                Od
            </th>
            <th>
                Predmet
            </th>
            <th>
                Čas
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.receivedMessages)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.From)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>

                <td>
                    <a class="btn btn-default pull-right" aria-label="Right Align" href=@Url.Action("Detail", "Spravy")>
                        Otvoriť
                        <span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span>
                    </a>
                </td>
            </tr>
        }

    </table>
</div>
<div>
    <a class="btn btn-default " aria-label="Right Align" href=@Url.Action("Index")>        
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a> | 
    <a class="btn btn-default " aria-label="Right Align" href=@Url.Action("Nova")>
        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        Nová
    </a> |
    <a class="btn btn-default " aria-label="Right Align" href=@Url.Action("Odoslane")>
        <span class="glyphicon glyphicon-saved" aria-hidden="true"></span>
        Odoslané
    </a>
</div>