E-Tombola/Controllers/TombolaController.cs
using E_Tombola.Models.Core;
using E_Tombola.Models.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E_Tombola.Controllers
{
    public class TombolaController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();
        //
        // GET: /Tomboly/
        public ActionResult Index()
        {          
                List<Raffle> model = unitOfWork.RaffleRepository.Get().Where(r => r.IsActive).OrderBy(r => r.DateOfDrawing).ToList();
                return View(model);          
        }


        //
        // GET: /Tomboly/KupListky/5
        [Authorize]
        public ActionResult KupListky(int id)
        {
            if (!User.IsInRole("Administrator"))
            {
                TicketPurschaseViewModel model = new TicketPurschaseViewModel();
                model.raffle = unitOfWork.RaffleRepository.GetByID(id);
                if (model.raffle != null)
                {
                    return View(model);
                }
                else
                {
                    TempData["msg"] = "Tombola s ID: "+id+" neexistuje";
                    return View("Error");
                }
            }
            TempData["msg"] = "Táto funkcia nieje prístupná pre administrátora";
            return View("Error");
        }

        //
        // POST: /Tomboly/KupListky/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult KupListky(TicketPurschaseViewModel model)
        {
            if (ModelState.IsValid)
            {
                Raffle raffle = unitOfWork.RaffleRepository.GetByID(model.raffle.Id);
                if (raffle != null && raffle.EndOfTicketSale>DateTime.Now)
                {
                    Profile profile = unitOfWork.ProfileRepository.Get().Single(p => p.UserName.Equals(User.Identity.Name));
                    if (profile != null)
                    {
                        if (profile.Credits >= (raffle.PriceOfTicket * model.Count))
                        {
                            profile.Credits = profile.Credits - raffle.PriceOfTicket * model.Count;
                            for (int i = 0; i < model.Count; i++)
                            {
                                unitOfWork.TicketRepository.Insert(new Ticket() { PurchaseDate = DateTime.Now, RaffleId = raffle.Id, UserName = User.Identity.Name });
                            }
                            unitOfWork.Save();
                            TempData["msg"] = model.Count + " lístkov bolo zakúpených";
                            return RedirectToAction("Index", "Profil");
                        }
                        TempData["msg"] = "Nedostatok kreditov! Zakúpte kredit.";
                        return RedirectToAction("Index", "Kredit");
                    }
                    return View("Error");
                }
                return View("Error");
            }
            return View(model);
        }

        public ActionResult Archiv()
        {
            List<Raffle> model = unitOfWork.RaffleRepository.Get().Where(m => !m.IsActive).OrderBy(m => m.DateOfDrawing).ToList();
            return View(model);
        }

        //
        // ZREBOVANIE

        public ActionResult Zrebovanie()
        {
            if((bool)HttpContext.Application["Zrebovanie"])
            {
                Raffle raffle = unitOfWork.RaffleRepository.GetByID((int)HttpContext.Application["ZrebovanieId"]);
                ViewBag.Message = "true";
                return View(raffle);
            }
            else
            {
                ViewBag.Message = "false";
                return View();
            }
            
        }
	}
}

E-Tombola/Views/Tombola/Archiv.cshtml
@{
    ViewBag.Title = "Archiv";
}

<h2><span class="glyphicon glyphicon-time"></span> Archív tombol</h2>

<hr />
@if (Model.Count==0) { <h2>! <small>Archív je prázdný</small></h2>}
@foreach (var item in Model)
{
    <div class="jumbotron" style="background:url('@Url.Content(item.ImageURL)') no-repeat center center">
        <div class="row">
            <div class="col-md-8">
                <h1>@item.Title</h1>
                <p class="lead">@item.Description</p>
            </div>
            <div class="col-md-4 tombola_caption">
                <div>
                    <p>Hodnota ceny: @item.Price &#8364</p>
                    <p>Počet predaných lístkov: @item.Tickets.Count</p>
                    <p>
                        Dátum žrebovania: <br />
                        @item.DateOfDrawing

                    </p>
                    <p>Výherný lístok: @item.WinnerTicketId </p>
                    
                </div>
            </div>
        </div>
    </div>
}
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

E-Tombola/Views/Tombola/Index.cshtml
@model IEnumerable<E_Tombola.Models.Core.Raffle>

@{
    ViewBag.Title = "Tomboly";
}


<h2><span class="glyphicon glyphicon-gift"></span> Aktívne tomboly</h2>

<hr />
@foreach(var item in Model)
{ 
<div class="jumbotron" style="background:url('@Url.Content(item.ImageURL)') no-repeat center center">
    <div class="row">
        <div class="col-md-8">
            <h1>@item.Title</h1>
            <p class="lead">@item.Description</p>
        </div>
        <div class="col-md-4 tombola_caption">
            <div>
                <p>Skúste štastie a zapojte sa do tomboly</p>
                <p>Hodnota ceny: @item.Price &#8364</p>
                <p>Počet lístkov: @item.Tickets.Count</p>
                <p>
                    Dátum žrebovania: <br />
                    @item.DateOfDrawing

                </p>
                @if (item.EndOfTicketSale > DateTime.Now)
                {
                    <p>Predaj lístkov končí o <span id="countdown1">@((item.EndOfTicketSale - DateTime.Now).Days) dni</span></p>

                    <p><a href=@Url.Action("KupListky", "Tombola", new { id = item.Id }) class="btn btn-success btn-large">Kúp tombolový lístok &raquo;</a></p>
                }
                else
                {
                    <p><strong>Predaj lístkov skončil.</strong></p>
                }
                </div>
        </div>
    </div>
</div>
}
<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Archiv")">
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        Archív tombol
    </a>
</div>

E-Tombola/Views/Tombola/KupListky.cshtml
@model E_Tombola.Controllers.TicketPurschaseViewModel

@{
    ViewBag.Title = "Kúp Listky";
}

<h1>Kúpiť tombolové lístky </h1>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        

        <h2><span class="glyphicon glyphicon-gift"></span> @Model.raffle.Title</h2>
        <hr />
        <div class="jumbotron" style="background:url('@Url.Content(Model.raffle.ImageURL)') no-repeat center center">
            <div class="row">
                <div class="col-md-8">
                    <h1>@Model.raffle.Title</h1>
                    <p class="lead">@Model.raffle.Description</p>
                </div>
                <div class="col-md-4 tombola_caption">
                    <div>
                        <p>Skúste štastie a zapojte sa do tomboly</p>
                        <p>Hodnota ceny: @Model.raffle.Price &#8364</p>
                        <p>Počet lístkov: @Model.raffle.Tickets.Count</p>
                        <p>
                            Dátum žrebovania: <br />
                            @Model.raffle.DateOfDrawing

                        </p>
                        <p>Koniec predaja lístkov o <span id="countdown1">@(Model.raffle.EndOfTicketSale.Subtract(DateTime.Now).Days) dni</span></p>
                        
                    </div>
                </div>
            </div>


        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.raffle.Id)
            @Html.HiddenFor(model => model.raffle.Title)
            @Html.HiddenFor(model => model.raffle.Description)
            @Html.HiddenFor(model => model.raffle.ImageURL)
            @Html.HiddenFor(model => model.raffle.Price)
            @Html.HiddenFor(model => model.raffle.PriceOfTicket)
            @Html.HiddenFor(model => model.raffle.DateOfCreation)
            @Html.HiddenFor(model => model.raffle.DateOfDrawing)
            @Html.HiddenFor(model => model.raffle.StartOfTicketSale)
            @Html.HiddenFor(model => model.raffle.EndOfTicketSale)
            @Html.HiddenFor(model => model.raffle.IsActive)
            @Html.HiddenFor(model => model.raffle.NumberOfTickets)
            @Html.LabelFor(model => model.Count, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Count)
                @Html.ValidationMessageFor(model => model.Count)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kúpiť lístky" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default" aria-label="Left Align" href="@Url.Action("Index")">
        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
        Späť
    </a>
</div>

E-Tombola/Views/Tombola/Zrebovanie.cshtml
@model E_Tombola.Models.Core.Raffle
@{
    ViewBag.Title = "Zrebovanie";
}

<h2><span class="glyphicon glyphicon-globe"></span> Sledujete LIVE prenos zo žrebovania</h2>
<hr />
<div class="jumbotron" style="background:url('@Url.Content(Model.ImageURL)') no-repeat center center">
    <div class="row">
        <div class="col-md-8">
            <h1>@Model.Title</h1>
            <p class="lead">@Model.Description</p>
        </div>
        <div class="col-md-4 tombola_caption">
            <div>
                <p>Hodnota ceny: @Model.Price &#8364</p>
                <p>Počet lístkov: @Model.Tickets.Count</p>
                <p>
                    Dátum žrebovania: <br />
                    @Model.DateOfDrawing
                </p>           
            </div>
        </div>
    </div>
</div>

<div id="VideoHolder">
    video....
</div>